Update .local/bin/brainrepo

diff --git a/private_dot_local/bin/executable_brainrepo b/private_dot_local/bin/executable_brainrepo
--- a/private_dot_local/bin/executable_brainrepo
+++ b/private_dot_local/bin/executable_brainrepo
@@ -1,8 +1,23 @@
 #!/usr/bin/env bash
 
-if ! (git diff --exit-code origin/master..master >/dev/null) ||
-  ! (git diff --exit-code master >/dev/null) ||
+if [ -d "$HOME/Documents/dev/My-Brain/" ]; then
+  cd ~/Documents/dev/My-Brain/
+else
+  printf "\nMy Brain directory not found\n"
+  exit 0
+fi
+
+if ! (git diff --exit-code origin/main..main >/dev/null) ||
+  ! (git diff --exit-code main >/dev/null) ||
   ! [[ -z "$(git status --porcelain)" ]]; then
-  echo "Your local repo has some changes that aren't pushed to origin/master ."
+  printf "\nYour local repo has some changes that aren't pushed to origin/main .\n"
+  printf "\nLet's take care of that for you.\n\n\n"
+  git add --all
+  git commit -m "updated on - $(date)"
+  git push origin main
   exit 1
+else
+  printf "\nYour local repo is up to date with origin/main .\n"
+  cd "$HOME"
+  exit 0
 fi
